// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yixtpfwsoknnogzccfvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpeHRwZndzb2tubm9nemNjZnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTE0MjIsImV4cCI6MjA2MTI4NzQyMn0.zrTdqMyApv5Kwqry_OJ4l7E_1PpHoSrk7NlYykA7nT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);